### ISSUE TITLE
BUG migration issue with add lecture notes

### ISSUE THREAD

**Issue by wabscale** [GusSand/Anubis#170]
The current prod is at alembic version `3890c28bd2cb`. I often will load the prod database locally before attempting to see if there are issues. There is some foreign key issue that is coming up here that is not coming up normally.

```
(venv) jc@aion ‹ master@ad1e982 › : ~/nyu/os/Anubis/api  
[0] % alembic upgrade head
Starting with DATABASE_URI: mysql+pymysql://anubis:anubis@127.0.0.1/anubis
Starting with CACHE_TYPE: RedisCache
Starting with SECRET_KEY: DEBUG
Starting with MINDEBUG: False
Starting with DEBUG: False
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 3890c28bd2cb -> c9f4c87534a5, ADD lecture notes
Traceback (most recent call last):
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1005, 'Can\'t create table `anubis`.`lecture_notes` (errno: 150 "Foreign key constraint is incorrectly formed")')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jc/nyu/os/Anubis/api/venv/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/config.py", line 559, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/config.py", line 553, in main
    self.run_cmd(cfg, options)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/config.py", line 530, in run_cmd
    fn(
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/script/base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "migrations/env.py", line 114, in <module>
    run_migrations_online()
  File "migrations/env.py", line 107, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/runtime/migration.py", line 561, in run_migrations
    step.migration_fn(**kw)
  File "/home/jc/nyu/os/Anubis/api/migrations/versions/c9f4c87534a5_add_lecture_notes.py", line 21, in upgrade
    op.create_table(
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/operations/ops.py", line 1087, in create_table
    return operations.invoke(op)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/operations/base.py", line 354, in invoke
    return fn(self, operation)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/ddl/impl.py", line 277, in create_table
    self._exec(schema.CreateTable(table))
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/ddl/impl.py", line 146, in _exec
    return conn.execute(construct, multiparams)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1262, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 77, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1352, in _execute_ddl
    ret = self._execute_context(
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1005, 'Can\'t create table `anubis`.`lecture_notes` (errno: 150 "Foreign key constraint is incorrectly formed")')
[SQL: 
CREATE TABLE lecture_notes (
	id VARCHAR(128) NOT NULL, 
	static_file_id VARCHAR(128) NOT NULL, 
	course_id VARCHAR(128) NOT NULL, 
	number INTEGER, 
	title TEXT, 
	description TEXT, 
	hidden BOOL, 
	created DATETIME, 
	last_updated DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(course_id) REFERENCES course (id), 
	FOREIGN KEY(static_file_id) REFERENCES static_file (id)
)

]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

```

**Comment by wabscale** [comment]
Not really sure what the deal with this issue is. Running a downgrade, then upgrade seems to make it work. I cannot explain what the issue here is.

```
(venv) jc@aion ‹ master@ad1e982 ● › : ~/nyu/os/Anubis/api  
[1] % alembic upgrade head                                  
Starting with DATABASE_URI: mysql+pymysql://anubis:anubis@127.0.0.1/anubis
Starting with CACHE_TYPE: RedisCache
Starting with SECRET_KEY: DEBUG
Starting with MINDEBUG: False
Starting with DEBUG: False
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 3890c28bd2cb -> c9f4c87534a5, ADD lecture notes
Traceback (most recent call last):
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1005, 'Can\'t create table `anubis`.`lecture_notes` (errno: 150 "Foreign key constraint is incorrectly formed")')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jc/nyu/os/Anubis/api/venv/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/config.py", line 559, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/config.py", line 553, in main
    self.run_cmd(cfg, options)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/config.py", line 530, in run_cmd
    fn(
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/script/base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/util/compat.py", line 184, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "migrations/env.py", line 114, in <module>
    run_migrations_online()
  File "migrations/env.py", line 107, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/runtime/migration.py", line 561, in run_migrations
    step.migration_fn(**kw)
  File "/home/jc/nyu/os/Anubis/api/migrations/versions/c9f4c87534a5_add_lecture_notes.py", line 21, in upgrade
    op.create_table(
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/operations/ops.py", line 1087, in create_table
    return operations.invoke(op)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/operations/base.py", line 354, in invoke
    return fn(self, operation)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/operations/toimpl.py", line 101, in create_table
    operations.impl.create_table(table)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/ddl/impl.py", line 277, in create_table
    self._exec(schema.CreateTable(table))
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/alembic/ddl/impl.py", line 146, in _exec
    return conn.execute(construct, multiparams)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1262, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 77, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1352, in _execute_ddl
    ret = self._execute_context(
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/jc/nyu/os/Anubis/api/venv/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1005, 'Can\'t create table `anubis`.`lecture_notes` (errno: 150 "Foreign key constraint is incorrectly formed")')
[SQL: 
CREATE TABLE lecture_notes (
	id VARCHAR(128) NOT NULL, 
	static_file_id VARCHAR(128), 
	course_id VARCHAR(128), 
	number INTEGER, 
	title TEXT, 
	description TEXT, 
	hidden BOOL, 
	created DATETIME, 
	last_updated DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(course_id) REFERENCES course (id), 
	FOREIGN KEY(static_file_id) REFERENCES static_file (id)
)

]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
(venv) jc@aion ‹ master@ad1e982 ● › : ~/nyu/os/Anubis/api  
[1] % alembic upgrade head
Starting with DATABASE_URI: mysql+pymysql://anubis:anubis@127.0.0.1/anubis
Starting with CACHE_TYPE: RedisCache
Starting with SECRET_KEY: DEBUG
Starting with MINDEBUG: False
Starting with DEBUG: False
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
(venv) jc@aion ‹ master@ad1e982 ● › : ~/nyu/os/Anubis/api  
[0] % alembic downgrade -1
Starting with DATABASE_URI: mysql+pymysql://anubis:anubis@127.0.0.1/anubis
Starting with CACHE_TYPE: RedisCache
Starting with SECRET_KEY: DEBUG
Starting with MINDEBUG: False
Starting with DEBUG: False
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running downgrade 65be3bf01dae -> c9f4c87534a5, CHG replace lecture notes number with post_time
(venv) jc@aion ‹ master@ad1e982 ● › : ~/nyu/os/Anubis/api  
[0] % alembic upgrade head
Starting with DATABASE_URI: mysql+pymysql://anubis:anubis@127.0.0.1/anubis
Starting with CACHE_TYPE: RedisCache
Starting with SECRET_KEY: DEBUG
Starting with MINDEBUG: False
Starting with DEBUG: False
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
(venv) jc@aion ‹ master@ad1e982 ● › : ~/nyu/os/Anubis/api  
[0] % alembic downgrade -1
Starting with DATABASE_URI: mysql+pymysql://anubis:anubis@127.0.0.1/anubis
Starting with CACHE_TYPE: RedisCache
Starting with SECRET_KEY: DEBUG
Starting with MINDEBUG: False
Starting with DEBUG: False
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running downgrade 65be3bf01dae -> c9f4c87534a5, CHG replace lecture notes number with post_time
(venv) jc@aion ‹ master@ad1e982 › : ~/nyu/os/Anubis/api  
[0] % alembic upgrade head
Starting with DATABASE_URI: mysql+pymysql://anubis:anubis@127.0.0.1/anubis
Starting with CACHE_TYPE: RedisCache
Starting with SECRET_KEY: DEBUG
Starting with MINDEBUG: False
Starting with DEBUG: False
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade c9f4c87534a5 -> 65be3bf01dae, CHG replace lecture notes number with post_time
(venv) jc@aion ‹ master@ad1e982 ● › : ~/nyu/os/Anubis/api  
[0] % alembic downgrade -1
Starting with DATABASE_URI: mysql+pymysql://anubis:anubis@127.0.0.1/anubis
Starting with CACHE_TYPE: RedisCache
Starting with SECRET_KEY: DEBUG
Starting with MINDEBUG: False
Starting with DEBUG: False
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running downgrade 65be3bf01dae -> c9f4c87534a5, CHG replace lecture notes number with post_time
(venv) jc@aion ‹ master@ad1e982 ● › : ~/nyu/os/Anubis/api  
[0] % alembic upgrade head
Starting with DATABASE_URI: mysql+pymysql://anubis:anubis@127.0.0.1/anubis
Starting with CACHE_TYPE: RedisCache
Starting with SECRET_KEY: DEBUG
Starting with MINDEBUG: False
Starting with DEBUG: False
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade c9f4c87534a5 -> 65be3bf01dae, CHG replace lecture notes number with post_time
(venv) jc@aion ‹ master@ad1e982 › : ~/nyu/os/Anubis/api  
[0] % mysql -u anubis -h 127.0.0.1 --password=anubis anubis 
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 66
Server version: 10.6.2-MariaDB-1:10.6.2+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [anubis]> desc lecture_notes;
+----------------+--------------+------+-----+---------+-------+
| Field          | Type         | Null | Key | Default | Extra |
+----------------+--------------+------+-----+---------+-------+
| id             | varchar(128) | NO   | PRI | NULL    |       |
| static_file_id | varchar(128) | NO   | MUL | NULL    |       |
| course_id      | varchar(128) | NO   | MUL | NULL    |       |
| title          | text         | YES  |     | NULL    |       |
| description    | text         | YES  |     | NULL    |       |
| hidden         | tinyint(1)   | YES  |     | NULL    |       |
| created        | datetime     | YES  |     | NULL    |       |
| last_updated   | datetime     | YES  |     | NULL    |       |
| post_time      | datetime     | YES  |     | NULL    |       |
+----------------+--------------+------+-----+---------+-------+
9 rows in set (0.000 sec)

MariaDB [anubis]> Bye

```
